1. Write a Python Program to Add Two Matrices?

Ans.

In [1]:
import numpy as np

# initialize matrices
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([[10,11,12], [13,14,15], [16,17,18]])

# add matrices
result = X + Y

# print result
print(result)


[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [9]:
def add_matrices(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    return result

# example usage
matrix1 = [[1,2,3], [4,5,6], [7,8,9]]
matrix2 = [[10,11,12], [13,14,15], [16,17,18]]
print(add_matrices(matrix1, matrix2))  


[[11, 13, 15], [17, 19, 21], [23, 25, 27]]


2. Write a Python Program to Multiply Two Matrices?

Ans.

In [5]:
import numpy as np

# initialize matrices
X = np.array([[1,2], [3,4], [5,6]])
Y = np.array([[7,8,9], [10,11,12]])
print(X)
print(Y)

# multiply matrices
result = np.dot(X, Y)

# print result
print(result)


[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [10]:
def multiply_matrices(matrix1, matrix2):
    # get dimensions
    rows1 = len(matrix1)
    cols1 = len(matrix1[0])
    rows2 = len(matrix2)
    cols2 = len(matrix2[0])
    
    # check if matrices can be multiplied
    if cols1 != rows2:
        print("Matrices cannot be multiplied.")
        return None
    
    # create result matrix filled with zeros
    result = [[0 for _ in range(cols2)] for _ in range(rows1)]
    
    # multiply matrices
    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
                
    return result

# example usage
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
print(multiply_matrices(matrix1, matrix2))  # output: [[30, 24, 18], [84, 69, 54], [138, 114, 90]]


[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


3. Write a Python Program to Transpose a Matrix?

Ans.


In [3]:
import numpy as np

# initialize matrix
X = np.array([[1,2], [3,4], [5,6]])

# transpose matrix
result = np.transpose(X)

# print result
print(result)


[[1 3 5]
 [2 4 6]]


In [11]:
def transpose_matrix(matrix):
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

# example usage
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(transpose_matrix(matrix))  # output: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]


[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


4. Write a Python Program to Sort Words in Alphabetic Order?

Ans.

In [6]:
import numpy as np

# initialize array of words
arr = np.array(['cat', 'dog', 'apple', 'banana'])

# sort words in alphabetic order
result = np.sort(arr)

# print result
print(result)


['apple' 'banana' 'cat' 'dog']


In [14]:
def sort_words(li):
    li.sort()
    return li

# example usage
li = ['cat', 'dog', 'apple', 'banana']
print(sort_words(li))  # output: "a hello is test this world"


['apple', 'banana', 'cat', 'dog']


5. Write a Python Program to Remove Punctuation From a String?

Ans.

In [7]:
import numpy as np

# initialize string
str = "Hello! This is a string with punctuation."

# remove punctuation
punc = np.array([ord(c) for c in "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"])
result = np.char.translate(str, {i:None for i in punc})

# print result
print(result)


Hello This is a string with punctuation


In [16]:
import string

my_string = "Hello, world!"
no_punctuation = my_string.translate(str.maketrans("", "", string.punctuation))

print(no_punctuation) # Output: Hello world


Hello world
